[build]
  # Het volledige pad naar de map waar de package.json in woont
  base = "/02_Next_starterkit_Pages_Components-main"
  
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"